### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by HonorJay** [chequanghuy/Character-Time-series-Matching#1]
hi. i have interest of this repository but actually i don't know yet which python version does you guys used.  could i know it?

**Comment by chequanghuy** [comment]
Python 3.6.9 or above is also OK with me

**Comment by HonorJay** [comment]
thanks. but i still have problems about requirements conflict cuz of torch==1.8.1 and torchvision==0.8.2. 

2023-07-14T04:43:56.705291746Z The conflict is caused by:
2023-07-14T04:43:56.705298565Z     The user requested torch==1.8.1
2023-07-14T04:43:56.705304796Z     thop 0.0.31.post2005241907 depends on torch>=1.0.0
2023-07-14T04:43:56.705310966Z     torchvision 0.8.2 depends on torch==1.7.1

could you sure that requirements are alright?

**Comment by wegiangb** [comment]
I used these 

Python v3.10 on colab

torch==2.0.1
torchvision==0.15.2

and yolov5==6.1

It seems to work for the Object detection 

This was another alternative
 
!pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html

It don't know how to find the model  yolov6m

**Comment by chequanghuy** [comment]
I have updated and fixed the previous issues. Sorry for the lateness.
