### ISSUE TITLE
How to find the model_yolo6m

### ISSUE THREAD

**Issue by wegiangb** [chequanghuy/Character-Time-series-Matching#2]
Hi 

It seems an excellent repo. 

I got the object detection working

I cannot get the character recognition working. 

How do I find the model_yolo6m and the link to the dataset is not functioning. 

It would be excellent to try it out.

**Comment by chequanghuy** [comment]
Hi @wegiangb this is the new link: https://drive.google.com/file/d/1U429KxS6SvoOMGoAGw0yQaDlLmBrLFgE/view?usp=sharing
