### ISSUE TITLE
can i train this model to make it detect some korean language also?

### ISSUE THREAD

**Issue by HonorJay** [chequanghuy/Character-Time-series-Matching#3]
if you know that way, could you let me know how to train for korean language on your readme.md?

**Comment by chequanghuy** [comment]
I am not familiar with the Korean license plate character set, but I am confident that if you can label the character detection problem for the characters on Korean license plates, you can do the same in English or Vietnamese.

**Comment by jeungmin717** [comment]
@HonorJay  
I am also interested in this topic : Making Korean Model for recognition
Have you figure out?
